### ISSUE TITLE
Tumbleweeds

### ISSUE THREAD

**Issue by 75lb** [codegl/tracegl#100]
Maintainer unseen since May 31st.

**Comment by 75lb** [comment]
I bought the product three months ago, stopped using it three days later.. It's _almost_ what i need but its usefulness is denied by the unresolved issues reported on this list. It's certainly not "commercial release" quality. 

At $15 it's more expensive than the vast majority of development tools on the Mac App Store - for an unfinished hobby project. 

Hopefully, a wonderful new release is about to drop very soon!

**Comment by codegl** [comment]
Hi Guys, sorry i haven't been updating traceGL a lot, i'm taking a different direction in the development. UI is going back to HTML and its getting integrated in a browser. This will fix nearly all of the issues that have been reported, and make it much easier to use. Its just going to take a while.

**Comment by 75lb** [comment]
can i have my money back please.

**Comment by 75lb** [comment]
I have sent a formal refund request to info@trace.gl with my Paypal details. Thanks.

**Comment by codegl** [comment]
Of course, no problem.

**Comment by 75lb** [comment]
Thanks.

I hope you have learned what a serious error you made selling untested, broken software, the development and users of which you abandoned until provoked into showing your face by this thread.. your response is a flimsy promise of a future rewrite which naturally no-one trusts nor gives credit to. 

Commercial release FAIL. You should refund all customers, today.

**Comment by stephen-uac** [comment]
I respectfully disagree 75lb. The tool may not be 100% complete (what tool ever is?), but it works in most capacities for most people. For anyone experiencing too many bugs in their individual setup, they can ask for a refund, but I have personally found the tool useful and worth every penny. The lack of updates has perhaps been frustrating, but understandable for an independent developer trying to find the best solution for his tool.

**Comment by datio** [comment]
The execution of the main functionality is great but the UI has its issues. Most of them relate to some text rendering bug.
Creating a bearable experience is hard. There are so many things to consider. Creating elements, such as the custom scrollbars, seems like an extravagance of time. (kudos for trying something new, though)

Using libraries to ease your life would be wiser, but even those available, aren't mature enough.

WebGL has more cons than pros for traceGL.
For example, fixing the font bug I opened [here](https://github.com/codegl/tracegl/issues/98) is quite unrealistic It'd require either the generation of a new bitmap each time new characters appear or it'd had to store the whole glyph collection of a font, which by the way creates even more issues to worry about. HTML works well, "features" such as the special characters fallback (in case the font doesn't support them) just work.

Watching what happens deeper under the hood is always cool.
Being a benchmark junkie, the price I paid for traceGL was worth it (I still have to use the plain old console.log and write code logic to filter stuff whenever there's a rendering problem though).

PayPal does not offer buyer protection for intangible goods. (kudos again for your ethics)
Maybe some negative PR wouldn't be so bad, it might have had reduced clients like the OP in the future.

**Comment by Marsup** [comment]
@codegl Maybe you should at least disable the payment form not to get anyone really angry.
If it gets integrated into a browser, what happens to the node side ?

**Comment by codegl** [comment]
I don't know yet what will happen to the node.js usecase yet, i might make it separately available. Also plenty of people seem to like the tool, if it doesn't work for you you are always free to ask for a refund.

**Comment by Marsup** [comment]
It works well for me (but only in firefox) even though it's not in my daily usage. I was just suggesting it if you're unsure of the near future.
