### ISSUE TITLE
Can't find files in parallel directory

### ISSUE THREAD

**Issue by johtso** [codegl/tracegl#11]
I'm using proxy mode, and I have a project structure something like this:

```
- /webapp/static/js/lib (URL: /static/js/lib)
 - vendor libs ...
- /webapp/static/js/src (URL: /static/js/src)
 - my source code
```

When opening a line in my text editor, it's only looking under the `src` directory, so my source code is mapped with no problems, but external libraries are not found.

Is there some way to specify the root folder it should search from?

**Comment by codegl** [comment]
Its using as its searchroot the 'current working directory' where you started tracegl, so if you start it higher up it should work. I could add a commandline arg for modifying this root.

**Comment by johtso** [comment]
Ah, so it's not magic!

That's perfect. Maybe a small note about source path mapping in the text editor section of the documentation would be good.

Thanks for creating such a fantastic tool!
