### ISSUE TITLE
trace.gl website down

### ISSUE THREAD

**Issue by tasinet** [codegl/tracegl#115]
Hi fellas, 

My company & I are currently getting heavy into node.js development and tracegl seems like a very worthwhile expense considering the debugging features that it provides [muchas kudos btw]. However, the trace.gl website seems to be down all day today (2013/12/06) - I've been getting a cloudflare error all day (Error 520 Ray ID: d8c2ac9292406e2 Web server is returning an unknown error).

I saw an older issue about cloudflare messing up with different browsers. Given that, I tested with Chrome (31), Safari 5.1.10 and Firefox 25.0.1 (all on Mac platform) and from different locations as well. The same cloudflare error page comes up each time. 

Please feel free to let me know if you need more info.

**Comment by richardwillars** [comment]
Spoke to Rik about this yesterday and he says it's down to a paypal issue and that the site will be back soon.

**Comment by Inviz** [comment]
I'd like to re-download trace.gl, but the website is down. Please return it back to life. Thanks

**Comment by floatdrop** [comment]
Sup, any info about domain?

**Comment by avetisk** [comment]
Now the website is back.

**Comment by doliver3** [comment]
Contrary to what avetisk says above, as of today when I tried, the website is still down. I have not seen it up in months. 

I get the following error on trace.gl:

Error 521 Ray ID: e4bfd17402003fa
Web server is down

Website is offline

The server may be down for maintenance, there may be a network problem, or the site may be experiencing excessive load.

Error is shown as a Host error on trace.gl. (not cloudflare or the browser).

**Comment by avetisk** [comment]
@doliver3, this is what I got from Rik one week ago when I asked him to send me my copy as the website was down:

> Hey,
> 
> Sorry my hosting has been rebooting all the time and i dont have autostart node stuff. Ill just send you a copy by mail when i get to my pc later today
> 
> Sent from my iPhone

So I guess, he still has the same issue with his hosting.

**Comment by alessioalex** [comment]
@codegl  @avetisk what is Rick's email? I cannot download trace.gl from the site now since it's down :( and I don't know what his email is :|

**Comment by rbarraud** [comment]
expired domain page there a day or 2 ago, now no connection to host :-/ When will this be fixed? I really want to get this thing!

**Comment by rbarraud** [comment]
How about putting something sensible into the github repository?
Suggestion: Encrypted .zip with password supplied, even if we have to get the key from the author via email...

**Comment by slikts** [comment]
Website down. Just piling in.

**Comment by Devric** [comment]
I know im being the next annoying person, but THE SITE IS DOWN, end of the world to me

**Comment by avetisk** [comment]
I guess it's time to release that the author won't leave his job to take care of this side project.

So basically let's just make a nice funeral on that.

**Comment by codegl** [comment]
Hi Guys, ive been working very hard to get traceGL into firefox free for everyone, and that thing is a completely new version of this. Sorry if i might appear apathetic about whats out there now. You can fetch a current version directly here for free: http://23.226.234.116/assets/share/tracegl.js
I will put it up opensource too, but the whole thing is entirely obsolete so i would rather not have to support it. The version in firefox is 100x faster and better in every way

**Comment by codegl** [comment]
Except it will take me a little while longer, i have just completed the new mixed mode HTML/GL UI toolkit for it, and its really fast also in HTML mode.

**Comment by codegl** [comment]
So in short, im working hard to get you all a much improved tracer, free.

**Comment by avetisk** [comment]
@codegl KUDOS \ o /

**Comment by Devric** [comment]
awesome!

**Comment by martindale** [comment]
+1, show us!

**Comment by jhnns** [comment]
:+1:

Pic or it didn't happen :wink:

**Comment by runelabs** [comment]
Excellent news getting this up there for Firefox :-)
Using node-inspector on Chrome is good, but Firefox is my preferred browser always.

**Comment by balupton** [comment]
@codegl perhaps time to open-source it and go for gittip for funding?

**Comment by balupton** [comment]
@codegl that link is no longer working, it's 404'ing

**Comment by juancampa** [comment]
+1 
It's down again. Just saying ;)

**Comment by vpassapera** [comment]
So, I was interested in purchasing this today..... seems like I'm SOL? (There isn't any alternative downloads either)

**Comment by codegl** [comment]
Here https://github.com/traceglMPL/tracegl

**Comment by jhnns** [comment]
Cool :+1:

**Comment by Inviz** [comment]
Man, thank you. This is the best thing you could do!

**Comment by dandv** [comment]
Awesome @codegl, thanks. Can we close this issue now?
