### ISSUE TITLE
Just stays stuck on "Checking for update..."

### ISSUE THREAD

**Issue by iamwilhelm** [codegl/tracegl#15]
When running it for a test file using vows, it just hangs on Checking for update.

```
 > node ~/bin/tracegl.js csg_test.js
[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://localhost:2000
[trace.GL] Checking for update...
```

I'm not sure what it's doing, or whether I should just let it keep running, or it's hanging on something. The csg_test.js file is one that uses vows, the testing framework.

**Comment by codegl** [comment]
Hmm. well the checking for update thing is async and in the background. It doesn't influence anything traceGL does so it shouldn't make a difference. It should report back 'up to date' though rather quickly.

**Comment by iamwilhelm** [comment]
I was running a script that took a while to get to a point that printed something. This was my mistake.
