### ISSUE TITLE
Coffee Script Support

### ISSUE THREAD

**Issue by interlock** [codegl/tracegl#26]
We write most of our stuff in coffee script now. It compiles down to JS of course, but it would be handy for development if we could run a command like this:

```
node tracegl app.coffee
```

**Comment by sansolovyov** [comment]
Source map support in general would be good addition as well...

**Comment by codegl** [comment]
I haven't found a good solution yet to trace coffeescript, except to rewrite a new tracer that parses and instruments coffeescript, which as you can imagine is a rather big project.

**Comment by sansolovyov** [comment]
How about source maps? Although they don't convey information about different variable names I'm afraid...

**Comment by BorisKourt** [comment]
+1 Also perhaps this would give some inspiration: http://www.youtube.com/watch?v=KsbPkbXmzmg

Also source maps were added via this: https://github.com/michaelficarra/CoffeeScriptRedux  as far as I know.

**Comment by davidgovea** [comment]
+1

```
node tracegl app.coffee
```

**Comment by namuol** [comment]
[Vanilla CoffeeScript 1.6.1+ supports Source Maps](http://coffeescript.org/#source-maps), FWIW.
