### ISSUE TITLE
Running CLI tests like jasmine and buster

### ISSUE THREAD

**Issue by interlock** [codegl/tracegl#27]
Any suggestions on how we could run our spec tests under tracegl?

Commands like these:

```
> npm run test-buster
> jasmine-node spec-jasmine/
```

**Comment by codegl** [comment]
Well the tracer can execute nodejs files like so
node tracegl filetoexec fileargs
You would have to figure out how these programs actually run from node.
I'm expecting jasmin-node to have a #!/bin/env node at the top of the file for instance.
If thats the case, you can just do node tracegl jasmin-node spec-jasmine
the npm run thing i'm less sure of, you'd have to investigate
