### ISSUE TITLE
Message order error xx yy

### ISSUE THREAD

**Issue by dgg23** [codegl/tracegl#28]
Proxying to VS2012 dev server and the widgets on the proxied page do not function and I get error messages like those shown in title in CLI from where node was launched. Some of the included js libs depend on others and everything is linked by a single html file and not any kind of script loader. Also one of the included libraries is kendoui which makes use of data-\* attributes for widget configuration.

In chome console various reference errors related to loading Sys from asp.net client side lib, jquery, kendo, and $ vars. Included js file source does appear in traceGL and I can see instrumented js files being returned in fiddler from requests but it seems to be causing problems.

**Comment by codegl** [comment]
Hmm thats not good, i will ask a friend of mine to test a vs2012 ASP project, see if he runs into anything odd.

**Comment by dgg23** [comment]
OK - I'm not sure how to interpret that message order error. What does it mean?

**Comment by dgg23** [comment]
Bump...

**Comment by codegl** [comment]
Hi, the easiest way for me to approach this is if you can give me a url where you have this stuff hosted, then i can try and run it through traceGL to see where it breaks it. I'm not on windows.

**Comment by dgg23** [comment]
It's an internal app with a back end database and no public URL... Do you have any idea what the nature of this message is?

**Comment by tanepiper** [comment]
@codegl I've got this too with one of my apps I tried.

The app is https://github.com/tanepiper/tweetifies.  When I try run it using v0.10.5, OSX 10.8.3 on MBA 2011 I get:

```
[trace.GL] WebGL trace UI: http://localhost:2000
[trace.GL] Checking for update...up to date.
Message order error 8986 8988
Message order error 8988 8990
```

It's very consistant that this happens, so might be able to help track the issue down.

**Comment by cmcculloh** [comment]
Happening for me too.

``` javascript
[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://localhost:2000
[trace.GL] Checking for update...Message order error 620 622
Message order error 626 621
Message order error 621 628
Message order error 632 634
Message order error 716 718
Message order error 718 717
Message order error 717 720
Message order error 720 722
```

**Comment by dgg23** [comment]
The idea was this was supposed to save me time but when it became clear that the author doesn't even have the ability to run asp.net I quickly shelved it as I don't really have time to debug debug tools :)

**Comment by cmcculloh** [comment]
I'm on Node.js; no asp.net involved for me...

**Comment by dgg23** [comment]
Maybe you'll get some support then.

**Comment by codegl** [comment]
Hi Guys, this bug is almost impossible for me to debug without running your project. The message ordering is rather strict. As soon as there are ordering errors, the callstack buildup goes skewed in the UI. I have locked down the message ordering as much as i can, the only thing that can skew it now are transcompile bugs, and i need your exact source to investigate those.

**Comment by codegl** [comment]
Also, getting a few message order errors is quite 'non fatal' if it will still show you your codeflow and will most of the time be harmless.

**Comment by codegl** [comment]
cmcculloh: You seem to have a rather serious ordering errors,are you running this on a single node.js backend? Usually when there are that many errors its actually tracing 2 things (ie opening a UI twice)

**Comment by dgg23** [comment]
It would be good if there were a trial version so people could make sure it actually works for their application before purchase.

**Comment by dgg23** [comment]
This isn't going anywhere so no point leaving an issue open that is never getting fixed.
