### ISSUE TITLE
Crash with "Error: socket hang up"

### ISSUE THREAD

**Issue by jomnius** [codegl/tracegl#31]
Not really sure whether this is TraceGL or my crash, because I couldn't figure out how to use TraceGL in the first place. While experimenting, something crashed (below). Reporting just in case.

Steps:
1) Start from command line (Mac OS X)
2) Open Firefox at localhost:2000
3) Nothing visible, blank TraceGL window
4) Open another Firefox window with the local index.html page
5) TraceGL still blank, try to do something
6) Random crash like below, think it must be my code doing something unexpected

[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://localhost:2000
[trace.GL] Checking for update...[trace.GL] Serving browser JS: http://localhost:2080
up to date.

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: socket hang up
    at createHangUpError (http.js:1360:15)
    at ServerResponse.OutgoingMessage._writeRaw (http.js:507:26)
    at ServerResponse.OutgoingMessage._send (http.js:476:15)
    at ServerResponse.OutgoingMessage.end (http.js:890:18)
    at endPoll (/Users/jounimiettunen/tracegl.js:3549:8)
    at Timer.<anonymous> (/Users/jounimiettunen/tracegl.js:3558:34)
    at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)

**Comment by jomnius** [comment]
Well, finally figured out difference between localhost 2000 (debug ui) vs 2080 (app ui). Still same crash, but now I can see that app ui is rendered incorrectly, doesn't load all CSS.

Guess the crash must be related to that, so I'll go debugging... Wonder why does it crash only with this setup, otherwise ok. Will update, when/if I have found out anything useful.

**Comment by jomnius** [comment]
Adding this codce into your tracegl.js helped a bit, but of course this is just handling side-effects of some real problem. Still I would prefer no crashes in any situation :)

```
process
.on("uncaughtException", function(e){
    console.log("uncaughtException");
    console.log(e);
    console.log(e.stack);
})
.on("error", function(e){
    console.log("error");
    console.log(e);
    console.log(e.stack);
});
```

Btw console output is this, in case it helps you to figure out what to do with the code...

```
uncaughtException
{ [Error: socket hang up] code: 'ECONNRESET' }
Error: socket hang up
    at createHangUpError (http.js:1360:15)
    at ServerResponse.OutgoingMessage._writeRaw (http.js:507:26)
    at ServerResponse.OutgoingMessage._send (http.js:476:15)
    at ServerResponse.OutgoingMessage.write (http.js:740:18)
    at ServerResponse.OutgoingMessage.end (http.js:882:16)
    at endPoll (/Users/jounimiettunen/tracegl.js:3561:8)
    at Object._onTimeout (/Users/jounimiettunen/tracegl.js:3752:13)
    at Timer.list.ontimeout (timers.js:101:19)
```

**Comment by codegl** [comment]
You could try turning off websockets. In traceGL.js at line
3756 add
no_websockets = 1
Did you try it with another nodejs version? like 0.8?

**Comment by jomnius** [comment]
Using node 0.8.20 locally, at Heroku 0.10.5. Had no idea, will update local version and try again. Thanx :)

Found commented line (below), will try if uncommenting makes any difference:
//var no_websockets = 1

Update: seems like updating locally to node.js 0.10.x was the only thing needed. Didn't even try no_websockets. Will close this now, was not a defect (even thought you might add those error handlers, but it's not related to this report).
