### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by emolaus** [codegl/tracegl#33]
I'm new to node and web dev, some input would be appreciated. I'd like to monitor my js running locally on a MAMP setup: localhost:8888/App/index.php

From the folder www/path/App I run 
node ~/tracegl -tgt:8888 .

But the tracegl UI is empty and the browser only displays "file not found".

Any clues?

**Comment by dustyjewett** [comment]
You'll want to use the [proxy setup](https://trace.gl/docs.html):

```
node ~/tracegl http://localhost:8888/
```

Then hit http://localhost:2080/App/index.php

**Comment by emolaus** [comment]
Thanks!
