### ISSUE TITLE
Add paypal support for payment?

### ISSUE THREAD

**Issue by DinisCruz** [codegl/tracegl#38]
I really don't want to put my Card details on your site :)

I'm happy to pay it via a paypal account, so can you set that up?

thanks

**Comment by codegl** [comment]
Im using the new way of doing creditcards, like Stripe. So what happens is the form is posted directly to the SSL gateway of paymill, and i get a token back to finalize the order. This way there is no creditcard data sent to my server. Also the site is delivered over SSL so there are no injections possible.

I'm investigating adding paypal though.

**Comment by LarryBattle** [comment]
This ticket should be closed. Paypal support as been added.
