### ISSUE TITLE
Settings file tracegl.json

### ISSUE THREAD

**Issue by navaru** [codegl/tracegl#41]
The docs refer to a `tracegl.json` file, but when I run `tracegl -settings` it creates a `.tracegl` file with default settings.

After I modified that file (also did the same with `tracegl.json`) and ran `node tracegl.js pathToStaticFolder`, the settings are not loaded.

**Comment by JeanHuguesRobert** [comment]
I am having the same issue

**Comment by Truebase-com** [comment]
I'm also having this issue.

Tried placing the file in all three places mentioned in https://trace.gl/docs.html ... no luck.
