### ISSUE TITLE
proxy does generate valid js code line 16098

### ISSUE THREAD

**Issue by shaunxcode** [codegl/tracegl#5]
specifically: 
         (;(_$_b.b14040=this._mouseStarted) ? (_$_.c(14041,this._mouseDrag(event))) : (_$_.c(14042,this._mouseUp(event))));

Notice the semicolon after the first paren.

**Comment by tgittos** [comment]
I'm also seeing this behavior, with the semicolon after the open paren.

**Comment by codegl** [comment]
Yep this is a bug, i'll go chase it down.

**Comment by codegl** [comment]
This bug is fixed.
