### ISSUE TITLE
Express App Requests

### ISSUE THREAD

**Issue by arb** [codegl/tracegl#50]
I am trying to use trace.gl to debug an Express app that is running on port 4000. When I start the app, trace.gl prints all of the files as expected. I hit the clear button because I'm really only interested in seeing and debugging the code on a per request basis. When I send requests through the app, the code visualization window doesn't rehydrate with the new code. Is this a setting issue or does trace.gl not function that way?

**Comment by mattpardee** [comment]
I noticed this too. It either doesn't process it or takes a very, very long time to output.

**Comment by codegl** [comment]
This should just work as expected, i have not been able to reproduce this bug.
What could be the case is that there is 'too much 'trace, although express shouldn't be so verbose. If you have a simple way for me to repro this, then i can fix it
