### ISSUE TITLE
Invoice page allows download without purchase

### ISSUE THREAD

**Issue by DinisCruz** [codegl/tracegl#52]
I noticed that the link for the download works with any url that starts with /pay

for example 

https://trace.gl/xxxx/pay12345     (replace xxxx with the correct URL version)

or 

https://trace.gl/xxxx/payABCD

ideally you should only allow downloads from transactions that actually ocured :)

**Comment by codegl** [comment]
I'l make the key some cryptographic hash then :)

**Comment by JamyDev** [comment]
I'm afraid this still works..
