### ISSUE TITLE
flowplayer-3.2.4.min.js has no source visible in the souce pane, just "*/"

### ISSUE THREAD

**Issue by AddictArts** [codegl/tracegl#54]
While it is minified and I don't really care that I can't see it I thought I would point it out since other minified sources do appear in the source pane.

![flowplayer](https://f.cloud.github.com/assets/911906/456515/f5a978c4-b36d-11e2-9b43-8bdb5febf589.png)

**Comment by codegl** [comment]
Yeah thats because its minified, its all on one line. Looks like this time  its off by one too. The fix for this is the pretty-print-before-transcompile feature.
