### ISSUE TITLE
Nothing happens when debugging DocPad

### ISSUE THREAD

**Issue by balupton** [codegl/tracegl#57]
So if I run [DocPad](http://docpad.org) without TraceGL, everything works fine:

```
$ docpad run
info: Welcome to DocPad v6.32.0
info: Plugins: cleanurls, coffeekup, coffeescript, downloader, eco, less, livereload, marked, partials, related, stylus, text
info: Environment: development
info: DocPad listening to http://localhost:9778/ on directory /Users/balupton/Projects/tb4-frontend/out
info: LiveReload listening to new socket on channel /docpad-livereload with log level 1
```

When trying to use it with tracegl, nothing happens:

```
$ tracegl -nolib ./node_modules/.bin/docpad run
[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://localhost:2000
[trace.GL] Checking for update...[trace.GL] Serving browser JS: http://localhost:2080
up to date.
```

and nothing happens at all. Screenshot: http://d.pr/i/Pe7l

**Comment by codegl** [comment]
Hi, it looks like its not really executing docpad at all, i've tried to install docpad using NPM but i'm getting pages and pages of errors, Error: No compatible version found: coffee-script@'coffee-script@~1.6.1'
that one being the most important. Can you check if docpad is properly NPM'ed at the moment?

**Comment by balupton** [comment]
Installing fine here, can you post the `npm-debug.log` file somewhere?

**Comment by codegl** [comment]
npm http GET https://registry.npmjs.org/docpad
npm http 200 https://registry.npmjs.org/docpad
npm http GET https://registry.npmjs.org/docpad/-/docpad-6.38.0.tgz
npm http 200 https://registry.npmjs.org/docpad/-/docpad-6.38.0.tgz
npm WARN engine docpad@6.38.0: wanted: {"node":">=0.8","npm":">=1.2"} (current: {"node":"v0.8.16","npm":"1.1.69"})
npm http GET https://registry.npmjs.org/typechecker
npm http GET https://registry.npmjs.org/bal-util
npm http GET https://registry.npmjs.org/ambi
npm http GET https://registry.npmjs.org/extendr
npm http GET https://registry.npmjs.org/eachr
npm http GET https://registry.npmjs.org/safefs
npm http GET https://registry.npmjs.org/taskgroup
npm http GET https://registry.npmjs.org/caterpillar
npm http GET https://registry.npmjs.org/caterpillar-filter
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/caterpillar-human
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/cson
npm http GET https://registry.npmjs.org/jschardet
npm http GET https://registry.npmjs.org/backbone/1.0.0
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/watchr
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/query-engine
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/getmac
npm http GET https://registry.npmjs.org/yamljs
npm http GET https://registry.npmjs.org/progressbar
npm http GET https://registry.npmjs.org/canihaz
npm http GET https://registry.npmjs.org/growl
npm http GET https://registry.npmjs.org/envfile
npm http 304 https://registry.npmjs.org/extendr
npm http 304 https://registry.npmjs.org/eachr
npm http 304 https://registry.npmjs.org/ambi
npm http 304 https://registry.npmjs.org/typechecker
npm http 200 https://registry.npmjs.org/bal-util
npm http GET https://registry.npmjs.org/bal-util/-/bal-util-2.1.0.tgz
npm http 304 https://registry.npmjs.org/safefs
npm http 304 https://registry.npmjs.org/taskgroup
npm http 304 https://registry.npmjs.org/caterpillar-filter
npm http 200 https://registry.npmjs.org/caterpillar
npm http GET https://registry.npmjs.org/caterpillar/-/caterpillar-2.0.3.tgz
npm http 200 https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/superagent/-/superagent-0.14.6.tgz
npm http 304 https://registry.npmjs.org/caterpillar-human
npm http 304 https://registry.npmjs.org/cson
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/jschardet
npm http 200 https://registry.npmjs.org/backbone/1.0.0
npm http GET https://registry.npmjs.org/backbone/-/backbone-1.0.0.tgz
npm http 304 https://registry.npmjs.org/watchr
npm http 304 https://registry.npmjs.org/mime
npm http 200 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express/-/express-3.2.5.tgz
npm http 200 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/query-engine
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/getmac
npm http 304 https://registry.npmjs.org/yamljs
npm http 304 https://registry.npmjs.org/progressbar
npm http 304 https://registry.npmjs.org/canihaz
npm http 200 https://registry.npmjs.org/bal-util/-/bal-util-2.1.0.tgz
npm http 200 https://registry.npmjs.org/caterpillar/-/caterpillar-2.0.3.tgz
npm http 304 https://registry.npmjs.org/growl
npm http 304 https://registry.npmjs.org/envfile
npm http 200 https://registry.npmjs.org/superagent/-/superagent-0.14.6.tgz
npm http 200 https://registry.npmjs.org/express/-/express-3.2.5.tgz
npm http 200 https://registry.npmjs.org/backbone/-/backbone-1.0.0.tgz
npm http GET https://registry.npmjs.org/ansistyles
npm http GET https://registry.npmjs.org/ansicolors
npm http GET https://registry.npmjs.org/progress/0.1.0
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/js2coffee
npm http GET https://registry.npmjs.org/eventemitter2
npm http GET https://registry.npmjs.org/joe
npm http GET https://registry.npmjs.org/bal-util
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/connect/2.7.10
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/formidable/1.0.9
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/send/0.1.0
npm http GET https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/mkdirp/0.3.4
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/js2coffee
npm http 304 https://registry.npmjs.org/ansistyles
npm http 304 https://registry.npmjs.org/progress/0.1.0
npm http 304 https://registry.npmjs.org/ansicolors
npm ERR! Error: ENOENT, lstat '/Users/user/test/node_modules/docpad/node_modules/progressbar/node_modules/progress/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 12.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "docpad"
npm ERR! cwd /Users/user/test
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69
npm ERR! path /Users/user/test/node_modules/docpad/node_modules/progressbar/node_modules/progress/.npmignore
npm ERR! fstream_path /Users/user/test/node_modules/docpad/node_modules/progressbar/node_modules/progress/.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack Writer._finish.er.fstream_finish_call (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26)
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/Users/user/test/node_modules/docpad/node_modules/caterpillar-human'
npm ERR! error rolling back  docpad@6.38.0 { [Error: ENOTEMPTY, rmdir '/Users/user/test/node_modules/docpad/node_modules/caterpillar-human']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/Users/user/test/node_modules/docpad/node_modules/caterpillar-human' }
npm ERR! Error: No compatible version found: js2coffee@'js2coffee@0.1.x'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.1.0","0.1.1","0.1.2","0.1.3","0.2.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:563:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:478:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 12.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "docpad"
npm ERR! cwd /Users/user/test
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69

**Comment by balupton** [comment]
Oh. DocPad requires npm v1.2, you've got v1.1. You can grab the latest with: `npm install -g npm`

**Comment by codegl** [comment]
Alright, i have it running as:
node tracegl.js -no:coffee-script path-to-docpad

**Comment by balupton** [comment]
Working beautifully, thanks!

``` bash
tracegl -no:coffee-script ~/Projects/bevry/docpad/bin/docpad run
```

**Comment by pflannery** [comment]
when I run docpad-trace run on windows I get

```
tracegl -no:coffee-script C:\Users\Peter\AppData\Roaming\npm\node_modules\docpad\bin/docpad run
[Error: Could not locate the tracegl executable path]
```

But I found that editing the docpad-trace command and including process.argv[0] got it to work

so now my docpad-trace command looks like this

```
var command = [
    process.argv[0],
    'tracegl',
    '-no:coffee-script',
    __dirname+'/docpad',
].concat(process.argv.slice(2));
```
