### ISSUE TITLE
Port is hard-coded to incorrect value in console output

### ISSUE THREAD

**Issue by cdata** [codegl/tracegl#58]
Line 382 reads as follows:

out("~~[trace.GL]~w~ WebGL trace UI: http://localhost:2000\n")

However, it should probably print that the trace UI is running on whatever port I set it to with the relevant config property. For example:

out("~~[trace.GL]~w~ WebGL trace UI: http://localhost:" + port + "\n")

This is also true for line 506, which prints the location where browser JS is being served.

**Comment by codegl** [comment]
Thanks, its going in the next release.
