### ISSUE TITLE
Trace will not render for SharePoint debugging.

### ISSUE THREAD

**Issue by dantuck** [codegl/tracegl#60]
I want to attach to a file in a SharePoint Layouts script folder but it is not working since that library relies on another.

```
c:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\14\TEMPLATE
\LAYOUTS\NG\Script\ActivityStream.js:3346
x,1);throw x;}})()));;_$_.e(3410,_$_b)}catch(x){_$_.e(3410,_$_b,x,1);throw x;}
                                                                           ^
ReferenceError: Type is not defined
    at Object.<anonymous> (c:\Program Files\Common Files\Microsoft Shared\Web Se
rver Extensions\14\TEMPLATE\LAYOUTS\NG\Script\ActivityStream.js:4:55)
    at Module._compile (module.js:449:26)
    at Module.m._compile (D:\bin\tracegl.js:42:22)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at Function.require (module.js:378:17)
    at nodeLoader (D:\bin\tracegl.js:48:10)
    at Object./trace/trace_server (D:\bin\tracegl.js:23:65)

```

Here is the top snippet of the file I am trying to trace

``` javascript
/// <reference name="MicrosoftAjax.debug.js" />
/// <reference name="jquery-1.4.2-vsdoc.js"/>

Type.registerNamespace('NG');

(function () {

    var $ = jQuery142;
    window.ngUserProfiles = window.ngUserProfiles || {};

    NG.ActivityView = function () { };
    NG.ActivityView.prototype =
    {
```

**Comment by codegl** [comment]
Hi,

TraceGL wraps everything in try/catch'es so it can unroll the callstack in case of exceptions.
Otherwise it'l loose track of the call-depth.
The error is in your code:
ReferenceError: Type is not defined  at Object.<anonymous> (c:\Program Files\Common Files\Microsoft Shared\Web Server Extensions\14\TEMPLATE\LAYOUTS\NG\Script\ActivityStream.js:4:55)

It says Type is undefined, and you execute this on it
Type.registerNamespace('NG');

I don't know why its not defined, but it has to be something in your code

**Comment by dantuck** [comment]
I may just not know how to attach to the js file properly. I was trying to follow the documentation but it was not really clear how to attach to a file that depends on another file. registerNamespace is injected by SharePoint so the file is not present in the same location as the activityStream.js.

**Comment by codegl** [comment]
Hi Dan, you don't attach it to a specific file, traceGL is either a file-server or a proxy, and transcompiles all JS that passes through it. You can use the commandline -do:file.js and -no:file.js to filter which files it processes.
