### ISSUE TITLE
Nitrous.IO support

### ISSUE THREAD

**Issue by JeanHuguesRobert** [codegl/tracegl#65]
I managed to get the UI on port 3000. However it displays nothing. I looked at the javascript console and saw:

initnew: 1044 linkos8-6702.euw1.actionbox.io:608
Falling back to polling 
CloseEvent {reason: "", code: 1006, wasClean: false, clipboardData: undefined, cancelBubble: false…}
 linkos8-6702.euw1.actionbox.io:9016
Websocket flooded, trace data lost linkos8-6702.euw1.actionbox.io:8946
Uncaught TypeError: Object 0 has no method 'send' linkos8-6702.euw1.actionbox.io:8959

The offending like 8959 is:
                } else ws.send(data)
Uncaught TypeError: Object 0 has no method 'send'
            }
        }

```
    //| send json message via xhr or websocket
```

This might be an issue with polling based websocket.

**Comment by codegl** [comment]
I will add a feature to turn off websockets on the commandline in the next release
