### ISSUE TITLE
Not logging client side code

### ISSUE THREAD

**Issue by cmcculloh** [codegl/tracegl#66]
Is there something special I have to do to get it to capture the client side stuff as well as the server side stuff?

I'm seeing all my node code execution, but, none of my client side execution. My impression was that this captured client side as well... is that wrong?

I can dig in and provide more detail, just wanted to make sure this was actually supposed to capture client side before I started digging in further... Thanks!

**Comment by codegl** [comment]
Hi, you have to explicity trace either front OR backend, it won't trace both in one go.
