### ISSUE TITLE
Using proxy setup with MAMP and custom domain name.

### ISSUE THREAD

**Issue by elsewares** [codegl/tracegl#69]
I'm attempting to monitor a Backbone application that I have running on MAMP with the local domain name of http://project.dev.  The tracegl server starts fine, but when I navigate to http://localhost:2080, I get the standard MAMP 'this VirtualHost has been set up' page, rather than the application.

**Comment by tanepiper** [comment]
@elsewares I've already submitted a patch for this that's been accepted: https://github.com/codegl/tracegl/issues/63

**Comment by elsewares** [comment]
@codegl When will this patch be available in the download?

**Comment by elsewares** [comment]
Note - I implemented the patch above manually.
