### ISSUE TITLE
Multiple and negated filters

### ISSUE THREAD

**Issue by Industrial** [codegl/tracegl#74]
I'd love to set several filters at a time, with an AND match, and filters that negate, hiding found entries instead of including them.

The main problem I have right now is that Highcharts uses a mousemoue event which spams the log madly. I want to ignore those rules (temporarily).

**Comment by codegl** [comment]
Its a bit of a kludge, but you can use negative regexps to filter out stuff
this filters out 'out' and 'replace' from the output when entered in the searchbox
/^(?!._out)(?!._replace)

**Comment by codegl** [comment]
also if you can match a whole file, an easy way would be use the commandline -no:highcharts
