### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by rhysbrettbowen** [codegl/tracegl#76]
getting this stack trace when connecting to http://localhost:2080

I'm running node v0.10.7 (latest) and getting the same error running in the cmd and cygwin (on windows 7)

stack trace gives:

{ [Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }
Error: Parse Error
    at Socket.socketOnData (http.js:1535:20)
    at TCP.onread (net.js:510:27)
uncaughtException
{ [Error: socket hang up] code: 'ECONNRESET' }
Error: socket hang up
    at createHangUpError (http.js:1424:15)
    at Socket.socketCloseListener (http.js:1474:23)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:451:12)

running with these commands: node tracegl.js https://localhost:28443

project runs through a tomcat server and I've tried openning http://localhost:2080 on both firefox and chrome.

also I usually get the certificate warning when running the project initially - not sure if that might be a cause

**Comment by codegl** [comment]
traceGL now has HTTPS support, this should fix your problem.
