### ISSUE TITLE
https support information

### ISSUE THREAD

**Issue by johnman** [codegl/tracegl#80]
Hi,

Don't know if this is the best place to ask but locally I am running a site under https as I am connecting to another https resource. Can I run the tracegl server as https (i already have mapped the hostname that I need but I need the https part)?

Thanks,

John

**Comment by johnman** [comment]
Having a quick scan it looks like there is the ability to specify use ssl but that is never passed in the constructor. Any plans to add support for this? Thanks.

**Comment by codegl** [comment]
https support is now in
