### ISSUE TITLE
BUG: Unable to trace CLI applications

### ISSUE THREAD

**Issue by 3rd-Eden** [codegl/tracegl#81]
I've got a race condition in of my CLI applications. I run the app using:

```
appname cdn --bump 1.2.0
```

So when using tracegl I expect I can trace the app using:

```
node ~/tracegl appname cdn --bump 1.2.0
```

Or call the bin file directly using

```
node ~/tracegl bin/foo cdn --bump 1.2.0
```

And it only outputs:

```
[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://localhost:2000
[trace.GL] Checking for update...[trace.GL] Serving browser JS: http://localhost:2080
up to date.
```

In the terminal. As you can see the script doesn't have an file extension because it's a CLI app. It does have a shebang (`#!/usr/bin/env node`). However when I add a symlink to the CLI app so it has a file extension it works as intended:

```
node ~/tracegl bin/foo.js cdn --bump 1.2.0

[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://localhost:2000
[trace.GL] Checking for update...up to date.
2013-05-27 12:01:56 debug:    [versions] The pub connections is established
2013-05-27 12:01:56 debug:    [versions] The sub connections is established
2013-05-27 12:01:56 debug:    [versions] The pub connections is ready
2013-05-27 12:01:56 debug:    [versions] The sub connections is ready

.. and more cli app output here ..
```

Suggested fix is checking if the supplied first argument is either accepted as parsed argument or to maybe use `--` as indicator that the rest of the passed in arguments should be used as node code. The `--` is something that the argument parsers [Argh](/observing/argh) and optimist are using.

**Comment by codegl** [comment]
I'm now checking if the argument is a local file, and ifso it runs in nodejs CLI mode.

**Comment by 3rd-Eden** [comment]
Works great, thanks for the fix.
