### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by 75lb** [codegl/tracegl#83]
The day after I bought the product the website is taken down, a little concerning.. I waited 24 hours but it's still down.. What's the current state of the project? Can you offer any reassurance?

**Comment by codegl** [comment]
The website is not down at all, working perfectly here. Project is being worked on right now. No worries.

**Comment by 75lb** [comment]
how super strange.. i was getting "could not connect to host" (http://trace.gl) errors in Safari 6.. restarted the browser, now it works. 

thankfully it was just a false alarm!

On 30 May 2013, at 10:26, codegl notifications@github.com wrote:

The website is not down at all, working perfectly here. Project is being worked on right now. No worries.

**Comment by codegl** [comment]
Yeah Cloudflare bugged, it was down indeed. I hope it keeps working.

**Comment by 75lb** [comment]
i have some other issues, like regular "Message order errors" and the below.. will post an proper issue when i understand the problem better.

```
mba:gsp Lloyd$ node ~/tracegl.js .
[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://localhost:2000
[trace.GL] Checking for update...[trace.GL] Serving browser JS: http://localhost:2080
up to date.
```

    
    fs.js:1051
        throw errnoException(process._errno, 'watch');
              ^
    Error: watch EMFILE
        at errnoException (fs.js:1019:11)
        at FSWatcher.start (fs.js:1051:11)
        at Object.fs.watch (fs.js:1076:11)
        at Object.w.watch (/Users/Lloyd/tracegl.js:4480:15)
        at /Users/Lloyd/tracegl.js:4624:31
        at Object.cb [as oncomplete](fs.js:168:19)

On 30 May 2013, at 10:34, codegl notifications@github.com wrote:

Yeah Cloudflare bugged, it was down indeed. I hope it keeps working.

**Comment by codegl** [comment]
What version of node.js are you using

**Comment by 75lb** [comment]
$ node -v
v0.10.7

$ npm -v
1.2.21

On 30 May 2013, at 10:46, codegl notifications@github.com wrote:

What version of node.js are you using

**Comment by codegl** [comment]
Ok so the file error is really strange, because the file is found, but watching on it fails.
For now you could comment out line 4624 and see if that helps
you could also do console.log(file) above it see what file seems to bug

**Comment by 75lb** [comment]
i think the issue is related to OS-level constraints (i'm on a Mac) on the maximum number of files which can be watched at any one time (see https://github.com/joyent/node/issues/2479)..

Unfortunately, there are almost 42,000 files in the project i'm working on.. an option to disable the "watch" mode would be useful here.. 

On 30 May 2013, at 10:58, codegl notifications@github.com wrote:

Ok so the file error is really strange, because the file is found, but watching on it fails.
For now you could comment out line 4624 and see if that helps
you could also do console.log(file) above it see what file seems to bug

**Comment by codegl** [comment]
Allright i'll add a -nowatch flag for your particular case
