### ISSUE TITLE
Feature Request: Disable Tracing On Specified Functions

### ISSUE THREAD

**Issue by ghost** [codegl/tracegl#96]
A key part of the architecture of my program parses function bodies and generates new code based on the findings.

This is a problem because TraceGL appears to be mangling the bodies in order to inject the tracing code.

Is there a way how I can disable tracing on specified functions?

**Comment by Truebase-com** [comment]
Closing my own issue...realized this is possible with some minor reworking of my code, and using the "-no" command line option.
